### ISSUE TITLE
A little problem running on iPhone：The widget has no results due to performance limitations

### ISSUE THREAD

**Issue by huang-xinjie** [hshsilver/Scriptable-Widget-MTA-Subway-Train-Reminder#1]
Great work! This must be a painstaking project.
The widget has no results due to performance limitations, when running on an iPhone(12).
runInApp的时候，显示是没有问题的，不过在小组件里运行的时候，只提示要获取位置信息，完了小组件就没显示结果了。
这项目泰裤辣，我调小组件调吐血了，也写了1kloc+做了几个界面。我好好参考下你的用法。
另外想咨询一下，有没有遇到多个小组件调同一个脚本传不同参数的时候，几个小组件之间的结果错乱的问题。
感谢！

**Comment by hshsilver** [comment]
1. 毕竟是依附于Scriptable的脚本，考虑下在设置里检查下Scriptable的位置权限是否授权？
2. Scriptable对不同iOS版本可能支持不同，例如API也不同。
3. 我没有遇到过结果错乱问题，因为每一个脚本的数据是互不相干的。

**Comment by huang-xinjie** [comment]
位置权限是已经有了的，在App里能正常运行，不过时间比较长（可能是有墙的缘故）
我是使用不同的参数调用同一个脚本，类似limit/marker+智能叠放来实现获取多个页面结果。
既然你没有遇到过，那就不打扰了o(*￣︶￣*)o
